name: first-grid-test
favicon: null
layout_spectrum: 0.00606384570710361
typography_spectrum: 0.4877303293906152
title: seyself
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1bbb7'
    - '#002b45'
    - '#7e7d82'
    - '#ebeeff'
    - '#99134a'
  brandStrength: 0.5625
  lightness: 0.7123335325159132
  saturation: 0.3853978351689875
  rhythmicContrast: 0.7999468508642167
purpose: []
