name: first-grid-test
favicon: null
layout_spectrum: 0.00606384570710361
typography_spectrum: 0.28812
title: seyself
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2f3437'
    - '#b8bbaa'
    - '#748ca8'
    - '#fbe21b'
  brandStrength: 0.3125
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
